feat(Tic Tac Toe):Added sound effect to win and draw state.
malivinayak/Tic-Tac-Toe pull request #20
Opened 2023-10-07 08:05 UTC by shivam-sharma-03

**Description**:
This Pull Request is a significant enhancement for the malivinayak Tic Tac Toe project, for the issue #19 , introducing an exciting new feature: Sound effect when the player win the game or when the game is a draw. Leveraging my expertise in HTML, CSS, and JavaScript, I've meticulously added these sound effects for enjoyable user experience also i have modified the look/ interface of the game to give it a modern look .

**Changes Made**:

Game Interface: Changed the UI of the game by giving the boxes different color adding borders shadows etc. . This will provide modern and engaging gameplay experience.

Sound Effects: To elevate the overall gaming experience, I've integrated sound effects that trigger when the game concludes. This addition adds an immersive dimension to the game, enhancing the player's enjoyment.

**Related Issue**:
This Pull Request directly addresses and resolves issue #19 .

**Checklist**:
Before merging this Pull Request, I have diligently ensured the following:

[x]The code adheres to the project's coding style and conventions.
[x]The Tic Tac Toe game's styling has been meticulously reviewed for cross-browser compatibility.

**Screenshots**:
I have included screenshots of the Tic Tac Toe game in action to provide a visual representation of the changes made. You can access these screenshots in the "Screenshots" section of this Pull Request.

**Testing**:

[x]I have thoroughly tested the Tic Tac Toe game to verify that it functions flawlessly.
[x]The sound effects have been tested and confirmed to play appropriately upon game conclusion.
[x]The game's compatibility across various browsers has been validated through testing.

**Additional Context**:
Please review the changes introduced in this Pull Request. The addition of the Tic Tac Toe game significantly enhances the project's interactivity and appeal. Your feedback is highly appreciated, and once approved, this exciting feature will be integrated into the project.

Checklist:

[x]I have reviewed the code changes and am confident they are correct.
[x]I have tested the Tic Tac Toe game thoroughly to ensure it functions as intended.
[x]I have provided relevant context and details in this PR description.
[x]I have attached screenshots to visually showcase the changes.
[x]I have confirmed the project's coding style and cross-browser compatibility.
[x]I have linked this PR to the related issue #19 .

**Screenshots**:

![Tic Tac Toe](https://github.com/malivinayak/Tic-Tac-Toe/assets/114740865/8e9b970f-e903-4b9a-9e3b-47121bee5b6d)
![Tic Tac Toe1](https://github.com/malivinayak/Tic-Tac-Toe/assets/114740865/0f3904ea-2386-4913-abe7-2b6c4d8c7947)

2023-10-07 18:37 UTC, malivinayak requested changes
You have done really good job.
Due to multiple contributions currently this branch has merge conflicts.
<details><summary>Solution:</summary>
<p>
You can rebase the branch</p>
</details> 

Once branch conflicts are resolved and requested minor changes are done request the review again so that I can merge the PR after review

2023-10-07 18:37 UTC, malivinayak commented on winsound.mp3
Add this file at assets/sound

2023-10-07 18:37 UTC, malivinayak commented on gametie.mp3
Add this file at assets/sound

2023-10-07 18:37 UTC, malivinayak commented on assets/js/script.js
Looks Good!👍

2023-10-08 04:47 UTC, shivam-sharma-03 commented
Thank you for your feedback doing the described things right away.
Also can you merge this pr as soon as possible because the hactoberfest themselves have a seven day review period, which will take a lot of time and ten it'll let me know whether this PR will count or not.
________________________________
From: Vinayak Mali ***@***.***>
Sent: Sunday, October 8, 2023 12:07 AM
To: malivinayak/Tic-Tac-Toe ***@***.***>
Cc: Shivam Sharma ***@***.***>; Author ***@***.***>
Subject: Re: [malivinayak/Tic-Tac-Toe] feat(Tic Tac Toe):Added sound effect to win and draw state. (PR #20)

Please be cautious
This email was sent outside of your organisation
________________________________

@malivinayak requested changes on this pull request.

You have done really good job.
Due to multiple contributions currently this branch has merge conflicts.

Solution:

You can rebase the branch

Once branch conflicts are resolved and requested minor changes are done request the review again so that I can merge the PR after review

________________________________

On winsound.mp3<https://github.com/malivinayak/Tic-Tac-Toe/pull/20#discussion_r1349559411>:

Add this file at assets/sound

________________________________

On gametie.mp3<https://github.com/malivinayak/Tic-Tac-Toe/pull/20#discussion_r1349559450>:

Add this file at assets/sound

________________________________

On assets/js/script.js<https://github.com/malivinayak/Tic-Tac-Toe/pull/20#discussion_r1349559700>:

Looks Good!👍

—
Reply to this email directly, view it on GitHub<https://github.com/malivinayak/Tic-Tac-Toe/pull/20#pullrequestreview-1663096545>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/A3LM5ALT7VSJYSR7WBL3VKDX6GOPPAVCNFSM6AAAAAA5WYF6VKVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTMNRTGA4TMNJUGU>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-10-08 04:57 UTC, shivam-sharma-03 commented on gametie.mp3
Added the sounds to the assets ->sound.

2023-10-08 05:08 UTC, shivam-sharma-03 commented
hey @malivinayak  I have completed the requested task.
please review this PR again.
issue #19 .

2023-10-08 05:56 UTC, malivinayak requested changes
https://github.com/malivinayak/Tic-Tac-Toe/assets/66154908/d77914c5-3019-4db3-87b4-ca2af0278b5f

I have encountered following bugs, you have to resolve this:
- [ ] Player's turn is not updating
- [ ] Rules button is not working anymore
- [ ] After win/draw, reload perform but after that player turn label doesn't show up unless we manually refresh the page

2023-10-08 09:41 UTC, shivam-sharma-03 commented
resolved the conflicts @malivinayak

2023-10-08 09:44 UTC, shivam-sharma-03 commented
I have fixed following bugs:

[x]Player's turn is not updating
[x]Rules button is not working anymore
[x]After win/draw, reload perform but after that player turn label doesn't show up unless we manually refresh the page

2023-10-08 09:55 UTC, closed without merging