updated
malivinayak/Tic-Tac-Toe pull request #27
Opened 2023-10-09 09:32 UTC by Hareesh061

Hi there, 
I made some initial changes in your repository. Please check out and merge my PR's.

GitHub: https://github.com/Hareesh061/Tic-Tac-Toe/tree/initial_change (PR's from)

UserName: Hareesh061

Thank you..
Keep learing...

2023-10-09 12:02 UTC, malivinayak requested changes

2023-10-09 12:02 UTC, malivinayak commented on assets/css/index.css
> +  background-image: linear-gradient(75deg, #9ff2fd, #974cf8 48%, #f66060);
poor visibility due to bg

2023-10-10 04:49 UTC, Hareesh061 commented
I'm updated the bg.  Please check it out. 

Username: Hareesh061

GitHub: https://github.com/Hareesh061/Tic-Tac-Toe/tree/initial_change

link: https://hareesh061.github.io/Tic-Tac-Toe

2023-10-10 05:47 UTC, malivinayak approved these changes

2023-10-10 05:47 UTC, merged